/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rjrafmgjtuuqtprmfhwc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqcmFmbWdqdHV1cXRwcm1maHdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNjMxNjksImV4cCI6MjA4NjgzOTE2OX0.P-m-C58t2KJ8cfBQhd_oFidRa_Vm6b0RhZBz1PJlq4s"