/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tnglakseiftgmdoxtapf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZ2xha3NlaWZ0Z21kb3h0YXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzODUxOTIsImV4cCI6MjA3Nzk2MTE5Mn0.valPBF1SH1-8C-k6VvLaZ7Ui8fmVnN0h7Y8eWz_-5w4"